#!/usr/bin/env bash
#loops from 1 to 10, in 4 print bad luck, in 8 print good luck.
#else prints Best School.
i=1

while [ $i -le 10 ]
do
	if [ $i = 4 ]
	then
		echo "bad luck"
	elif [ $i = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i+1 ))
done
