#!/usr/bin/env bash
#displays time for 12 hrs and 59 mins
hours=0

while [ $hours -le 12 ]
do
	mins=1
	echo "Hour: $hours"
	while [ $mins -lt 60 ]
	do
		echo "$mins"
		((mins++))
	done

	((hours++))
done
